repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.34.0'
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/psf/black
    rev: '22.3.0'
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.961'
    hooks:
      - id: mypy
        args: ["--install-types", "--non-interactive", "--show-error-codes"]
        additional_dependencies:
          - appdirs==1.4.4
          - bencode.py==4.0.0
          - genutility==0.0.86
          - qbittorrent-api==2022.5.32
          - requests==2.28.0
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
